language: node_js

matrix:
  include:
    - name: Bundle size
      script: yarn workspace website bundlesize
    - name: Test Website
      script: yarn workspace website test
    - name: Test Studio
      script: yarn workspace sanity-studio test
